// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIvYkuZYcE7eNbz11T7t0Vgi-KjwgBe_w',
    appId: '1:739758999902:web:b6e4b6e223f8587bfc27cf',
    messagingSenderId: '739758999902',
    projectId: 'vibbra-f4822',
    authDomain: 'vibbra-f4822.firebaseapp.com',
    storageBucket: 'vibbra-f4822.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz3b5tD5pT8kIDawN8eWs-xwPpdJxQj4Q',
    appId: '1:739758999902:android:4208b10d02ef63dcfc27cf',
    messagingSenderId: '739758999902',
    projectId: 'vibbra-f4822',
    storageBucket: 'vibbra-f4822.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd9PuqzT38eszxh1_EOKCC4222lZjSlP4',
    appId: '1:739758999902:ios:80ed8c9bd69e5044fc27cf',
    messagingSenderId: '739758999902',
    projectId: 'vibbra-f4822',
    storageBucket: 'vibbra-f4822.appspot.com',
    iosClientId: '739758999902-jr1v5ifctqutu1p4bcp6v26s4r17f1ks.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibbraTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd9PuqzT38eszxh1_EOKCC4222lZjSlP4',
    appId: '1:739758999902:ios:80ed8c9bd69e5044fc27cf',
    messagingSenderId: '739758999902',
    projectId: 'vibbra-f4822',
    storageBucket: 'vibbra-f4822.appspot.com',
    iosClientId: '739758999902-jr1v5ifctqutu1p4bcp6v26s4r17f1ks.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibbraTest',
  );
}
